### PR TITLE
Tile click functionality/change font

### PR DESCRIPTION
**Pull request by debjohnson33**
@joebuono @CymruRing @zpadela Please review my pull request when you get a minute. Thanks!

### CODE REVIEW

**Comment by zpadela** [comment]
@debjohnson33 Looks good!

**Review by joebuono — COMMENTED** [review]
@debjohnson33 This looks good! Does it properly format the products based on which one is selected? It looks like it should. I don't have much to say otherwise, nice job.

**Comment by CymruRing** [comment]
Were you able to get the selected box styling to work with dynamic renders?  I do not know enough to determine if so just reading the code.

**Comment by debjohnson33** [comment]
I was not able to get that yet, so I'm moving on to writing tests. I think
it will probably take a major refactor to get it to work.

**Pull request merged**
